### ISSUE TITLE
代码问题请教

### ISSUE THREAD

**Issue by pndx** [wyq2214368/laravel-jieba#5]
我参考你的代码来实现分词api，发现如果没有将以下这段代码放在控制器时，就没有达到常驻内存的效果，我只是在service provider中register中添加了绑定的代码，不太明白为什么控制器没有这段就达不到效果
https://github.com/wyq2214368/laravel-jieba/blob/56ecfdfc28def0c8b1640fecc7f62098c52b56a4/app/Http/Controllers/Api/JiebaController.php#L11-L23

**Comment by WYQilin** [comment]
> 我参考你的代码来实现分词api，发现如果没有将以下这段代码放在控制器时，就没有达到常驻内存的效果，我只是在service provider中register中添加了绑定的代码，不太明白为什么控制器没有这段就达不到效果
> 
> https://github.com/wyq2214368/laravel-jieba/blob/56ecfdfc28def0c8b1640fecc7f62098c52b56a4/app/Http/Controllers/Api/JiebaController.php#L11-L23

你没有声明和赋值这几个属性的话，对应方法里是怎么调用的对应jieba类？
是否常驻内存应该仅与使用了laravels有关
